# Generated by Django 3.1.6 on 2021-02-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210205_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_active',
            field=models.BooleanField(default=False),
        ),
    ]
